esxi_hostname="<hostname>"
esxi_username="root"
esxi_password="<password>"
esxi_datastore="datastore2"
loadcore_mdw_image_path="C:\\Users\\Downloads\\LoadCore-MDW-5.1.0-5385-398.ova"
management_network="VM Network"
vm_prefix="TF_LoadCore"